import type { Metadata } from "next";
import { Lato, Nunito_Sans } from "next/font/google";
import "./globals.css";

// Define Lato for headings (with 'variable' for CSS flexibility)
const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"], // Normal + Bold
  variable: "--font-heading", // CSS variable name
});

// Define Nunito Sans for body text
const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "600"], // Normal + Semi-bold
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Carrer Sathi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${nunitoSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
